version: '3.1'

services:
  postgres:
    image: postgres
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=perservant
    volumes:
      - perservant-db:/var/lib/postgresql/data:rw

volumes:
  perservant-db: